repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-merge-conflict
    -   id: check-byte-order-marker
    -   id: detect-private-key
    -   id: fix-encoding-pragma
    -   id: mixed-line-ending
    -   id: fix-encoding-pragma
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
